[package]
name = "shred"
version = "0.1.0"
authors = ["torkleyy"]
description = """
Dispatches tasks in parallel which need read access to some resources,
and write access to others.
"""
readme = "README.md"
documentation = "https://docs.rs/shred"
repository = "https://github.com/torkleyy/shred"
keywords = ["parallel", "tasks", "resources", "ecs"]
categories = ["concurrency"]
license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "torkleyy/shred" }

[dependencies]
fnv = "1"
mopa = "0.2"
shred-derive = { path = "shred-derive", version = "0.1.0" }

[dev-dependencies]
cgmath = "0.14"

[dependencies.rayon]
version = "0.7"
features = ["unstable"]
