[package]
name = "shred"
version = "0.6.0"
authors = ["torkleyy <torkleyy@gmail.com>"]
description = """
Dispatches systems in parallel which need read access to some resources,
and write access to others.
"""
readme = "README.md"
documentation = "https://docs.rs/shred"
repository = "https://github.com/slide-rs/shred"
keywords = ["parallel", "systems", "resources", "ecs"]
categories = ["concurrency"]
license = "MIT/Apache-2.0"
exclude = ["bors.toml", ".travis.yml"]

[badges]
travis-ci = { repository = "torkleyy/shred" }

[dependencies]
arrayvec = "0.4"
fxhash = "0.2"
mopa = "0.2"
rayon = { version = "0.9", optional = true }
shred-derive = { path = "shred-derive", version = "0.3" }
smallvec = "0.6"

[dev-dependencies]
cgmath = "0.16"

[features]
default = ["parallel"]
parallel = ["rayon"]

[[example]]
name = "async"
required-features = ["parallel"]

[[example]]
name = "basic_dispatch"

[[example]]
name = "custom_bundle"

[[example]]
name = "derive_bundle"

[[example]]
name = "fetch_opt"

[[example]]
name = "generic_derive"

[[example]]
name = "par_seq"
required-features = ["parallel"]

[[example]]
name = "seq_dispatch"

[[example]]
name = "thread_local"
